apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xhis
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0009-tenant/tkwch-fix-0075-0009-app/devfile-sample-xhis@sha256:9123280ef6b4e100461989ec301b5cc909b3fa306d23a02f4555eed0b7c3966a
        name: my-nodejs
        resources: {}
status: {}
