apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xhis
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xhis
    app.kubernetes.io/part-of: tkwch-fix-0075-0009-app
  name: devfile-sample-xhis
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xhis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xhis
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0009-tenant/tkwch-fix-0075-0009-app/devfile-sample-xhis@sha256:9123280ef6b4e100461989ec301b5cc909b3fa306d23a02f4555eed0b7c3966a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
